[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "CI='false' npm run build"
  publish = ".next"
  environment = { NEXT_PUBLIC_REACT_APP_URL = 'https://hackillinois.org' }

[functions]
  directory = "functions"